import {ZeroAddress,formatUnits} from 'ethers';
import {currentContainer,requireCurrentContainer} from './current-container.js';
import {resolveIdentity} from './rpc.js';
import {safeRpcMessage} from './rpc-http.js';
import {clearWalletProposal,walletProposalGeneration,assertWalletProposalCurrent,walletProposalClearKey,walletProposalClearedAfter} from './wallet-storage.js';
import {readWalletProposalLink,nativeWalletSymbol} from './wallet-links.js';
import {setupWalletSharing} from './wallet-sharing-ui.js';
import {getWallets,rememberWallet,inspectWallet,deployNotaryWallet,pendingWalletTx,recoverWalletTransaction,signWalletProposal,executeWalletProposal,verifyProposalState,checkWalletSignature,tokenDetails,walletSafety,walletHistory} from './wallet-client.js';
import {validateWalletProposal,newWalletProposal,mergeWalletProposals,walletDigest,exactAmount} from './wallet-protocol.js';
import './wallet.css';
const $=id=>document.getElementById(id),key='tapesign-wallet-v1:proposal';
export function setupWallet({onTabChange=()=>{}}={}){
 $('wallet-workspace').innerHTML=`
 <section class="hero"><div><div class="eyebrow">TWO APPROVALS. ONE TRANSFER.</div><h1>每一次转出，<br><em>由双方共同确认。</em></h1><p>独立交易钱包与 TapeOut 容器持有人共同签名。<br>资金由新建的双签合约钱包保管，普通钱包保持原样。</p></div><div class="hero-note"><span class="note-number">TAPESIGN / WALLET · 试验版</span><div>创建 → 双签激活 → 充值 → 双签转账</div><small>同链 · 原生币 / ERC20 · 无管理员单方转账</small></div></section>
 <p class="wallet-notice">试验功能，尚未经过独立安全审计，请先使用测试资产。两把密钥应独立保管；本版无找回、换绑或升级入口。转让电路 NFT 会阻止原授权继续执行，请先转出资产。NFT 回到原持有人时原授权可恢复，转让不等于永久撤销。</p>
 <nav class="tabs wallet-tabs" aria-label="公证钱包"><button data-wallet-tab="create" class="active">创建钱包</button><button data-wallet-tab="wallets">我的钱包</button><button data-wallet-tab="transfer">发起转账</button><button data-wallet-tab="sign">共同签署</button></nav>
 <p id="wallet-status" class="status" role="status">先在顶部选择用于公证授权的容器。</p>
 <section id="wallet-next-step" class="card wallet-next-step" hidden><h2 id="wallet-next-title"></h2><p id="wallet-next-text"></p></section>
 <section id="wallet-pending" class="card" hidden><h2>待确认的链上操作</h2><p id="wallet-pending-text" class="mono"></p><p id="wallet-pending-stage"></p><p id="wallet-pending-status" class="hint" role="status" aria-live="polite"></p><p class="hint">已知哈希会自动核对，不会重新发送。若钱包没有返回哈希，请从钱包活动粘贴原交易哈希；加速后可填入输入内容相同的替换交易哈希。</p><div class="input-row"><input id="wallet-recover-hash" aria-label="待恢复的交易哈希" placeholder="原交易 / 替换交易哈希（已知哈希可留空）"><button id="wallet-recover" class="button primary">立即核对交易结果</button></div><button id="wallet-diagnostics" class="text-button">复制排查信息（不含签名和私钥）</button><textarea id="wallet-diagnostics-text" readonly hidden aria-label="待确认交易排查信息"></textarea></section>
 <section id="wallet-create" class="card"><h2>创建公证钱包</h2><p class="selected-container" data-current-container></p><label for="wallet-controller">交易控制钱包地址</label><input id="wallet-controller" placeholder="0x…（与容器持有人不同的地址）" autocomplete="off"><p class="hint">创建时连接容器持有人钱包。部署后还需要交易方和容器方分别签署绑定，才会激活。部署与激活各有一笔交易费；两次离线签名本身不发交易。</p><label class="consent-check"><input id="wallet-risk" type="checkbox"><span>我已理解这是新的合约钱包地址，资金需在双签激活后转入，并理解本版没有密钥找回机制。</span></label><button id="wallet-deploy" class="button primary">钱包确认部署</button></section>
 <section id="wallet-wallets" class="card" hidden><div class="section-head"><h2>我的公证钱包</h2><button id="wallet-refresh" class="button secondary">刷新本机列表</button></div><p class="hint">这里保存本浏览器创建或导入的钱包，不代表全链搜索结果。换设备请导入钱包地址并重新核验。</p><div id="wallet-list"></div><label for="wallet-import-address">导入已有钱包合约</label><div class="input-row"><input id="wallet-import-address" placeholder="0x 合约地址"><button id="wallet-import" class="button secondary">按顶部容器核验并导入</button></div></section>
 <section id="wallet-transfer" class="card" hidden><h2>发起转账</h2><label for="wallet-select">选择公证钱包</label><div class="input-row"><select id="wallet-select"></select><button id="wallet-load" class="button secondary">读取链上状态</button></div><pre id="wallet-state" class="mono"></pre><div class="wallet-form"><div><label for="wallet-asset">转账资产</label><select id="wallet-asset"><option value="native">原生币（OKB / BNB）</option><option value="erc20">ERC20 代币</option></select></div><div><label for="wallet-token">代币合约地址（ERC20）</label><input id="wallet-token" placeholder="0x…" disabled></div></div><button id="wallet-balance" class="text-button">查询余额与代币精度</button><p id="wallet-balance-text" class="hint"></p><label for="wallet-recipient">收款地址</label><input id="wallet-recipient" placeholder="0x…"><div class="wallet-form"><div><label for="wallet-amount">转账金额</label><input id="wallet-amount" inputmode="decimal" placeholder="0.01"></div><div><label for="wallet-minutes">提案有效期（分钟）</label><input id="wallet-minutes" type="number" min="1" max="1440" value="30"></div></div><button id="wallet-propose" class="button primary">生成转账提案</button><div class="wallet-actions"><button id="wallet-binding" class="button secondary">生成双签激活提案</button><button id="wallet-resume" class="button secondary">生成双签恢复提案</button><button id="wallet-cancel" class="text-button">撤销当前序号</button><button id="wallet-pause" class="text-button">紧急暂停钱包</button></div><p class="hint">任意原签名方可暂停或撤销当前序号；恢复必须双签。充值地址仅在合约代码、身份和激活状态核验通过后展示。</p><div id="wallet-deposit" hidden><strong>充值到新建的合约钱包地址</strong><p id="wallet-deposit-address" class="mono"></p><p class="hint">仅同链原生币 / ERC20。不要转入 NFT 或跨链资产；本版没有这些资产的转出接口。</p></div></section>
 <section id="wallet-sign" class="card" hidden><h2>共同签署同一份提案</h2><p class="hint">先核对完整地址、资产、金额和有效期，再连接相应角色的钱包签名。交换 JSON 提案文件即可跨设备接力；导入文件不会自动签名或发送交易。</p><label class="import-label">导入提案或对方签名 <input id="wallet-proposal-file" type="file" accept=".json,application/json"></label><textarea id="wallet-proposal-json" rows="4" placeholder="也可以粘贴提案 JSON" aria-label="提案 JSON"></textarea><button id="wallet-proposal-import" class="button secondary">核对并导入提案</button><div id="wallet-proposal-view" hidden><pre id="wallet-review" class="mono wallet-review"></pre><div class="wallet-signatures"><div><strong>① 交易控制方</strong><p id="wallet-sign-a-state" class="hint"></p><button id="wallet-sign-a" class="button primary">交易钱包签名</button></div><div><strong>② 容器公证方</strong><p id="wallet-sign-b-state" class="hint"></p><button id="wallet-sign-b" class="button primary">容器持有人签名</button></div></div><div class="wallet-actions"><button id="wallet-export" class="button secondary">导出提案 / 签名文件</button><button id="wallet-verify" class="button secondary">重新核验双签与链状态</button><button id="wallet-execute" class="button primary">钱包确认执行</button></div><p class="hint">已有两份签名不代表交易已执行。最终执行需要一次链上交易，发送者支付 gas。合约只允许本笔绑定、转账或恢复操作。</p></div></section>`;
 let busy=false,active=false,tab='create',proposal=null,state=null,reviewReady=false,checking=false,pendingTimer=null,pendingDetail='',reconciled=null,pendingPhase='',pendingStarted=0,pendingTick=null,attempts=0,lastRecoveryError='',recoveryAbort=null;
 const sharing=setupWalletSharing();let incomingRole=null,lastLink='';
 $('wallet-sign').insertAdjacentHTML('beforeend','<div class="wallet-proposal-clear"><button id="wallet-clear-proposal" class="button secondary" type="button">清空当前提案及签名</button><p class="hint">只清空本机当前提案、签名和导入内容。钱包列表、余额、待确认交易和历史记录保留；已分享的签名不会因此撤销。</p><p id="wallet-clear-status" class="hint" role="status"></p></div>');
 $('wallet-sign').insertAdjacentHTML('afterbegin','<section id="wallet-link-incoming" class="wallet-incoming" hidden><p id="wallet-link-status" role="status"></p><button id="wallet-link-retry" class="button secondary" type="button">重新核验链接提案</button></section>');
 const note=(text,error=false)=>{$('wallet-status').textContent=text;$('wallet-status').classList.toggle('error',error);};
 function pending(){const p=pendingWalletTx();$('wallet-pending').hidden=!p;if(p){
  const stage=p.invalid?'待确认记录异常':p.details.kind==='deploy'?'当前第 1 步：确认新钱包部署。尚未进入交易控制方签名。':p.details.kind==='Bind'?'当前第 3 步：确认双签激活交易。':'正在确认已提交的'+({Transfer:'转账',Resume:'恢复',pause:'暂停',cancel:'撤销'}[p.details.kind]||'链上')+'操作。';
  const detail=p.invalid?'请保留原始记录，不能跳过核对。':!p.hash&&!pendingStarted?'未取得交易哈希，发送结果未知。'+(pendingDetail?pendingDetail+'。':'')+'现在没有进行自动查链；请从容器钱包的交易活动复制哈希后点击“立即核对交易结果”。':pendingStarted?pendingPhase+' · 本次 '+Math.floor((Date.now()-pendingStarted)/1000)+' 秒 / 最长 30 秒 · 第 '+attempts+' 次核对':pendingDetail||'等待核对已保存的交易；节点未同步时约每 8 秒重试。';
  $('wallet-pending-text').textContent=p.invalid?'本机待确认记录损坏，已阻止重复发送。':'链 '+p.chainId+' · '+(p.hash||'无交易哈希');
  $('wallet-pending-stage').textContent=stage;$('wallet-pending-status').textContent=detail;
  if(active&&(!busy||pendingStarted))note(stage+'\n'+detail,!!p.invalid||(!pendingStarted&&!!pendingDetail));
 }else pendingDetail='';return p;}
 function controls(){const elements=document.querySelectorAll('#wallet-workspace button,#wallet-workspace input,#wallet-workspace select,#wallet-workspace textarea');const p=pending();elements.forEach(b=>b.disabled=busy);$('wallet-token').disabled=busy||$('wallet-asset').value!=='erc20';$('wallet-execute').disabled=busy||!!p||!proposal||!reviewReady||Object.values(proposal.signatures).some(s=>s==='0x');for(const [id,role]of [['wallet-sign-a','transaction'],['wallet-sign-b','notary']])$(id).disabled=busy||!!p||!proposal||!reviewReady||proposal.signatures[role]!=='0x';$('wallet-copy-link').disabled=busy||!sharing.shareReady;if(state){$('wallet-binding').disabled=busy||state.active||state.ownerChanged;$('wallet-resume').disabled=busy||!state.active||!state.paused||state.ownerChanged;$('wallet-propose').disabled=busy||!state.active||state.paused||state.ownerChanged;}for(const id of ['wallet-deploy','wallet-pause','wallet-cancel'])$(id).disabled=busy||!!p;$('wallet-deploy').textContent=p?'等待上一笔交易核对':'钱包确认部署';$('wallet-execute').textContent=p?'交易待核对，勿重复发送':'钱包确认执行';$('wallet-recover').disabled=busy||checking||p?.invalid;$('wallet-clear-proposal').disabled=busy||checking;globalThis.dispatchEvent(new CustomEvent('tapesign:wallet-busy',{detail:busy}));}
 function schedulePending(delay=8000){clearTimeout(pendingTimer);pendingTimer=null;const p=pendingWalletTx();if(active&&!document.hidden&&p?.hash&&!p.invalid&&!checking)pendingTimer=setTimeout(()=>{pendingTimer=null;void reconcilePending();},delay);}
 async function readRecovery(hash){recoveryAbort=new AbortController();pendingStarted=Date.now();pendingPhase='连接核验节点';attempts++;clearInterval(pendingTick);pendingTick=setInterval(pending,1000);pending();controls();try{const generation=walletProposalGeneration(),pendingCreatedAt=pendingWalletTx()?.createdAt;return {...await recoverWalletTransaction(hash,{signal:recoveryAbort.signal,onProgress:stage=>{pendingPhase=stage;pending();}}),proposalGeneration:generation,pendingCreatedAt};}catch(e){lastRecoveryError=safeRpcMessage(e.shortMessage||e.message);throw e;}finally{clearInterval(pendingTick);pendingStarted=0;recoveryAbort=null;}}
 async function reconcilePending(hash){if(busy||checking)return;const p=pendingWalletTx();if(!p)return;checking=true;pendingDetail='';controls();try{reconciled=await readRecovery(hash);if(active&&!busy){await recovered(reconciled);reconciled=null;}}catch(e){if(pendingWalletTx()){pendingDetail=safeRpcMessage(e.shortMessage||e.message)+(pendingWalletTx()?.hash?'。保留原交易，约 8 秒后自动重试。':'');}else if(active)note(e.message,true);}finally{checking=false;controls();schedulePending();}}
 async function submittedResult(p){pendingDetail='';controls();note('交易已提交：'+p.hash+'。正在核对原交易，无需再次发送。');try{await recovered(await readRecovery());}catch(e){pendingDetail=safeRpcMessage(e.message)+'。保留原交易，后台自动重试。';note('交易已提交，无需重发。'+pendingDetail,true);}}
 function next(title,text){$('wallet-next-step').hidden=!title;$('wallet-next-title').textContent=title;$('wallet-next-text').textContent=text;}
 async function action(fn){if(busy||checking)return;clearTimeout(pendingTimer);busy=true;controls();note('正在核验或等待钱包确认，请勿重复提交…');try{await fn();}catch(e){if(pendingWalletTx()){pendingDetail=safeRpcMessage(e.shortMessage||e.message);lastRecoveryError=pendingDetail;}note(Number(e.code)===4001?'已取消钱包操作。':e.shortMessage||e.message,true);if(e.code==='WALLET_TX_PENDING')$('wallet-pending').scrollIntoView({block:'center'});}finally{busy=false;controls();schedulePending();queueMicrotask(consumeLink);}}
 function selected(){const value=$('wallet-select').value;const p=getWallets().find(p=>p.chainId+'/'+p.wallet.toLowerCase()===value);if(!p)throw Error('请先创建或导入公证钱包');return p;}
 function choose(policy){list();$('wallet-select').value=policy.chainId+'/'+policy.wallet.toLowerCase();}
 function list(){const old=$('wallet-select').value;$('wallet-select').replaceChildren();$('wallet-list').replaceChildren();const all=getWallets();if(!all.length){const p=document.createElement('p');p.className='hint';p.textContent='本机还没有公证钱包。创建后需双签激活。';$('wallet-list').append(p);}
  for(const p of all){const o=document.createElement('option');o.value=p.chainId+'/'+p.wallet.toLowerCase();o.textContent=p.name.replace('.tape','')+' · 链 '+p.chainId+' · '+p.wallet;$('wallet-select').append(o);const row=document.createElement('div');row.className='wallet-list-row';const text=document.createElement('p');text.className='mono';text.textContent=p.name.replace('.tape','')+' · 链 '+p.chainId+'\n'+p.wallet;const b=document.createElement('button');b.className='button secondary';b.textContent='打开 / 核验';b.onclick=()=>action(async()=>{choose(p);setTab('transfer');await load();});row.append(text,b);$('wallet-list').append(row);}if(all.some(p=>p.chainId+'/'+p.wallet.toLowerCase()===old))$('wallet-select').value=old;}
 async function load(snapshot){state=snapshot||await inspectWallet(selected());$('wallet-state').textContent='钱包 '+state.policy.wallet+'\n绑定容器 '+state.policy.name+'\n交易方 '+state.policy.transactionSigner+'\n容器签名方 '+state.policy.notarySigner+'\n序号 '+state.nonce+' · '+(state.ownerChanged?'容器持有人变化，已阻止执行':!state.active?'未激活，请双方签署绑定':state.paused?'已暂停':'已激活');$('wallet-deposit').hidden=!state.active||state.paused||state.ownerChanged;$('wallet-deposit-address').textContent=state.policy.wallet;sharing.showAccount(state.policy,{force:true});note('已读取链上钱包状态。');return state;}
 async function review(){reviewReady=false;controls();if(!proposal){$('wallet-proposal-view').hidden=true;sharing.clearProposal();return;}$('wallet-proposal-view').hidden=false;$('wallet-review').textContent='正在读取提案…';const p=proposal,m=p.message;let amount='';if(p.action==='Transfer'){const token=m.asset===ZeroAddress?{symbol:nativeWalletSymbol(p.policy.chainId),decimals:18}:await tokenDetails(p.policy,m.asset);amount='资产 '+token.symbol+'（'+m.asset+'）\n金额 '+formatUnits(m.amount,token.decimals)+' · 最小单位 '+m.amount+'\n收款 '+m.recipient+'\n';}
  if(proposal!==p)return;
  $('wallet-review').textContent=({Bind:'激活双签绑定',Transfer:'转账',Resume:'恢复已暂停钱包'}[p.action])+'\n链 '+p.policy.chainId+'\n公证钱包 '+p.policy.wallet+'\n容器 '+p.policy.name+'\n电路 NFT '+p.policy.circuit+' #'+p.policy.circuitTokenId+'\n容器账户 '+p.policy.container+'\n交易方 '+p.policy.transactionSigner+'\n容器签名方 '+p.policy.notarySigner+'\n'+amount+'序号 '+m.nonce+' · 权限版本 '+m.policyVersion+'\n有效期至 '+new Date(Number(m.deadline)*1000).toLocaleString()+'\n提案指纹 '+walletDigest(p);
  $('wallet-sign-a-state').textContent=p.signatures.transaction==='0x'?'等待签名':'签名已保存，执行前重新核验';$('wallet-sign-b-state').textContent=p.signatures.notary==='0x'?'等待签名':'签名已保存，执行前重新核验';reviewReady=true;const handoff=sharing.review(p,incomingRole);next(p.action==='Bind'&&p.signatures.transaction==='0x'?'钱包已部署，下一步：双方签署激活':handoff.title,handoff.message);controls();}
 async function save(p,generation){assertWalletProposalCurrent(generation);$('wallet-clear-status').textContent='';proposal=validateWalletProposal(p);localStorage.setItem(key,JSON.stringify(proposal));await review();assertWalletProposalCurrent(generation);}
 async function make(actionName){const generation=walletProposalGeneration(),s=await load();if(s.ownerChanged)throw Error('电路 NFT 持有人已变化');let opts={minutes:Number($('wallet-minutes').value)};if(actionName==='Transfer'){const token=await tokenDetails(s.policy,$('wallet-asset').value==='native'?ZeroAddress:$('wallet-token').value.trim());opts={...opts,asset:token.asset,recipient:$('wallet-recipient').value.trim(),amount:exactAmount($('wallet-amount').value,token.decimals)};if(BigInt(opts.amount)>BigInt(token.balance))throw Error('公证钱包余额不足');}
  const p=newWalletProposal(s.policy,actionName,s.nonce,opts);await verifyProposalState(p);await save(p,generation);setTab('sign');note('提案已生成，尚未发送交易。请分别完成两方签名。');}
 async function importProposal(raw,{role=null}={}){const generation=walletProposalGeneration();if(raw.length>100000)throw Error('提案文件过大');let p=validateWalletProposal(JSON.parse(raw));await verifyProposalState(p);if(proposal&&walletDigest(proposal)===walletDigest(p))p=mergeWalletProposals(proposal,p);else if(proposal&&!confirm('替换当前本机提案？旧签名不会被合并。'))return false;for(const r of ['transaction','notary'])if(p.signatures[r]!=='0x')await checkWalletSignature(p,r,p.signatures[r]);assertWalletProposalCurrent(generation);rememberWallet(p.policy);choose(p.policy);incomingRole=role;await save(p,generation);note('提案身份与链上状态已核验，导入未发送交易。');return true;}
 function consumeLink(){
  if(!active||tab!=='sign'||!location.hash.startsWith('#wallet/sign?'))return false;
  const source=location.hash;if(source===lastLink)return true;if(busy||checking)return true;lastLink=source;
  $('wallet-link-incoming').hidden=false;reviewReady=false;$('wallet-proposal-view').hidden=true;controls();
  if(pendingWalletTx()){$('wallet-link-status').textContent='本机已有待确认交易，请先核对原交易，再点击重新核验链接提案。未覆盖原记录。';return true;}
  void action(async()=>{
   $('wallet-link-status').textContent='正在核验链接中的提案、容器身份与已有签名；不会自动签名或发送交易。';
   try{const value=readWalletProposalLink(location.href);if(!value)throw Error('链接缺少提案参数');$('wallet-proposal-json').value=JSON.stringify(value.proposal,null,2);
    const imported=await importProposal($('wallet-proposal-json').value,{role:value.role});
    if(!imported){$('wallet-link-status').textContent='已取消导入，原本机提案保留。';return;}
    $('wallet-link-status').textContent='链接提案已核验并导入。请按下方角色指引核对、签名；导入没有发送交易。';
    if(location.hash===source){history.replaceState(null,'',location.pathname+location.search+'#wallet/sign');lastLink='';}
   }catch(e){$('wallet-link-status').textContent='链接导入失败：'+safeRpcMessage(e.message)+'。原本机提案未被替换。';throw e;}
  });return true;
 }
 $('wallet-link-retry').onclick=()=>{lastLink='';consumeLink();};
 for(const event of ['hashchange','popstate'])window.addEventListener(event,()=>consumeLink());
 async function recovered(r){const generation=r.proposalGeneration;choose(r.policy);setTab('transfer');const s=await load(r.state);$('wallet-recover-hash').value='';if(r.kind==='deploy'&&!s.active){if(generation!==walletProposalGeneration()||walletProposalClearedAfter(r.pendingCreatedAt)){note('部署已确认。当前提案已清空，需要时可生成新的双签激活提案。');return;}await save(newWalletProposal(s.policy,'Bind',s.nonce,{minutes:30}),generation);setTab('sign');note('部署已打包并回读。已自动生成双签激活提案，请先让交易控制方签名。');}else{if(proposal&&r.digest===walletDigest(proposal)){proposal=null;reviewReady=false;localStorage.removeItem(key);$('wallet-proposal-json').value='';await review();}next(r.kind==='Bind'?'双签激活已执行，可向新地址充值':'本次操作已执行',r.kind==='Bind'?'双方的绑定签名已通过合约核验。受双签约束的是下方新合约地址中的资产。':'执行交易 '+r.hash+' 已打包并回读。已完成的提案不会继续展示为待签任务。');note('交易已打包并回读：'+r.hash+'。可继续查询钱包状态和余额。');}}
 function clearProposalView(){
  proposal=null;reviewReady=false;incomingRole=null;lastLink='';sharing.clearProposal();
  $('wallet-proposal-json').value='';$('wallet-proposal-file').value='';$('wallet-proposal-view').hidden=true;$('wallet-review').textContent='';$('wallet-link-incoming').hidden=true;$('wallet-link-status').textContent='';next('','');
  if(location.hash.startsWith('#wallet/sign?'))history.replaceState(null,'',location.pathname+location.search+'#wallet/sign');
  controls();$('wallet-clear-status').textContent='当前提案及签名已清空。钱包列表、余额、待确认交易和历史记录均保留。';
 }
 $('wallet-clear-proposal').onclick=()=>{if(busy||checking)return;try{clearWalletProposal();clearProposalView();}catch(e){note(e.message,true);}};
 $('wallet-deploy').onclick=()=>action(async()=>{if(!$('wallet-risk').checked)throw Error('请先阅读并确认试验版规则');const name=requireCurrentContainer();if(!confirm('将部署新的双签合约钱包，需要 gas。创建后仍需两方签署激活，确认继续？'))return;await submittedResult(await deployNotaryWallet(name,$('wallet-controller').value.trim()));});
 $('wallet-recover').onclick=()=>void reconcilePending($('wallet-recover-hash').value.trim());
 $('wallet-diagnostics').onclick=async()=>{const p=pendingWalletTx();const data={page:location.origin+location.pathname,tab:location.hash.split('?')[0],chainId:p?.chainId||null,transactionHash:p?.hash||null,operation:p?.details?.kind||null,createdAt:p?.createdAt||null,wallet:p?.details?.policy?.wallet||null,container:p?.details?.policy?.name||null,currentStage:pendingPhase,lastError:lastRecoveryError||pendingDetail,attempts};const text=JSON.stringify(data,null,2);$('wallet-diagnostics-text').hidden=false;$('wallet-diagnostics-text').value=text;try{await navigator.clipboard.writeText(text);$('wallet-diagnostics').textContent='排查信息已复制';}catch{$('wallet-diagnostics-text').select();$('wallet-diagnostics').textContent='请复制下方排查信息';}};
 $('wallet-import').onclick=()=>action(async()=>{const name=requireCurrentContainer(),{chainId}=await resolveIdentity(name);const s=await inspectWallet({name,chainId,wallet:$('wallet-import-address').value.trim()});rememberWallet(s.policy);list();note('钱包已通过代码与容器核验，保存到本机。');});
 $('wallet-refresh').onclick=()=>{list();note('本机钱包列表已刷新，打开时读取链上状态。');};$('wallet-load').onclick=()=>action(load);$('wallet-select').onchange=()=>{state=null;$('wallet-state').textContent='请读取所选钱包的链上状态。';$('wallet-deposit').hidden=true;$('wallet-balance-text').textContent='';sharing.showAccount(selected(),{force:true});};
 $('wallet-asset').onchange=()=>{controls();$('wallet-balance-text').textContent='';};$('wallet-balance').onclick=()=>action(async()=>{const s=await load(),b=await tokenDetails(s.policy,$('wallet-asset').value==='native'?ZeroAddress:$('wallet-token').value.trim());$('wallet-balance-text').textContent=b.formattedBalance+' '+b.symbol+' · 精度 '+b.decimals;});
 $('wallet-propose').onclick=()=>action(()=>make('Transfer'));$('wallet-binding').onclick=()=>action(()=>make('Bind'));$('wallet-resume').onclick=()=>action(()=>make('Resume'));
 for(const mode of ['pause','cancel'])$('wallet-'+mode).onclick=()=>action(async()=>{if(!confirm(mode==='pause'?'暂停钱包并作废当前序号，恢复需要双签。继续？':'撤销当前序号会使已有提案签名失效，需要支付 gas。继续？'))return;await submittedResult(await walletSafety(selected(),mode));});
 $('wallet-proposal-import').onclick=()=>action(()=>importProposal($('wallet-proposal-json').value));$('wallet-proposal-file').onchange=()=>action(async()=>{const f=$('wallet-proposal-file').files[0];if(!f)return;if(f.size>100000)throw Error('提案文件过大');await importProposal(await f.text());});
 for(const [id,role]of [['a','transaction'],['b','notary']])$('wallet-sign-'+id).onclick=()=>action(async()=>{if(!proposal)throw Error('请先生成或导入提案');const generation=walletProposalGeneration();await review();if(!confirm('请核对页面显示的完整提案。即将请求'+(role==='transaction'?'交易方':'容器持有人')+'签名。'))return;assertWalletProposalCurrent(generation);await save(await signWalletProposal(proposal,role),generation);note('签名已保存，接力链接已更新。请按上方指引复制新链接，交给下一方签署或提交执行。');});
 $('wallet-verify').onclick=()=>action(async()=>{await verifyProposalState(proposal);for(const role of ['transaction','notary'])await checkWalletSignature(proposal,role,proposal.signatures[role]);await review();note('双签与当前链上状态核验通过，尚未执行交易。');});
 $('wallet-execute').onclick=()=>action(async()=>{await verifyProposalState(proposal);await review();if(!confirm('两份签名将提交到合约执行，发送钱包需支付 gas。确认执行页面显示的这份提案？'))return;await submittedResult(await executeWalletProposal(proposal));});
 $('wallet-export').onclick=()=>{if(!proposal)return;const url=URL.createObjectURL(new Blob([JSON.stringify(proposal,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='TapeSign-wallet-'+proposal.action+'-'+proposal.message.nonce+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 function setTab(name,{notify=true}={}){if(!['create','wallets','transfer','sign'].includes(name))return;tab=name;for(const t of ['create','wallets','transfer','sign'])$('wallet-'+t).hidden=t!==name;document.querySelectorAll('[data-wallet-tab]').forEach(b=>b.classList.toggle('active',b.dataset.walletTab===name));if(name==='wallets'||name==='transfer'){list();if(getWallets().length)sharing.showAccount(selected());}sharing.setVisible(active&&name!=='create');if(notify)onTabChange(name);}
 document.querySelectorAll('[data-wallet-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.walletTab));
 window.addEventListener('tapesign:container',()=>{document.querySelectorAll('#wallet-workspace [data-current-container]').forEach(e=>e.textContent=currentContainer().replace('.tape','')||'请在顶部选择容器');});
 try{const saved=localStorage.getItem(key);if(saved){proposal=validateWalletProposal(JSON.parse(saved));$('wallet-proposal-json').value=JSON.stringify(proposal,null,2);}}catch{note('本机提案无法读取，请重新导入；未自动删除原记录。',true);}
 window.addEventListener('storage',event=>{if(event.key===walletProposalClearKey||(event.key===key&&event.newValue===null)){clearProposalView();return;}if(event.key?.startsWith('tapesign-wallet-v1:')||event.key===null){controls();schedulePending(0);}});
 document.addEventListener('visibilitychange',()=>schedulePending(0));
 list();controls();return {get busy(){return busy;},get tab(){return tab;},setTab,activate(value){active=value;clearTimeout(pendingTimer);sharing.setVisible(active&&tab!=='create');if(active){controls();if(consumeLink()){}else if(reconciled&&!checking)void action(async()=>{await recovered(reconciled);reconciled=null;});else if(pendingWalletTx()){pending();schedulePending(0);}else if(proposal)void action(async()=>{await review();note('已恢复本机提案；签署和执行前将重新核验链上状态。');});else note(currentContainer()?'当前容器 '+currentContainer().replace('.tape','')+'。可创建钱包，或导入已有钱包 / 提案。':'请先在顶部选择容器。');}}};
}
